- hosts: all
  vars:
    var12: Default
  tasks:
  - name: "copy nginx.conf"
    copy:
      src: nginx.conf
      dest: /etc/nginx/nginx.conf
    become: true
    notify: "Restart nginx"
    
  handlers:
  - name: "Restart nginx"
    service:
      name: nginx
      state: restarted


- hosts: newgroup
  tasks:
  - name: "Install mysql-client"
    apt:
      name: mysql-client
      state: present
      update_cache: true
    become: true

- hosts: demo
  tasks:
  - name: "echo a command"
    shell:
      cmd: echo "{{ var12 }}" >> file.txt
    

